name: Python package

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: main-linux-amd64
            pathsep: ':'
          - os: windows-latest
            asset_name: main-windows-amd64.exe
            pathsep: ';'
          - os: macos-latest
            asset_name: main-macos-amd64
            pathsep: ':'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt pyinstaller
    - name: PyInstall
      run: pyinstaller --add-data 'assets${{ matrix.pathsep }}assets' main.py --name ${{ matrix.asset_name }} --onefile --windowed -y
    - name: Verify app
      if: matrix.os == 'ubuntu-latest'
      run: ./dist/${{ matrix.asset_name }}
    - name: Make executable
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: chmod +x ./dist/${{ matrix.asset_name }}
    - name: Current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Upload app
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: dist/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ steps.date.outputs.date }}
        overwrite: true
